stages:
  - test

image: maven:latest

test-account-management:
  stage: test
  tags:
    - shared-fi
  script:
    - 'cd account-management'
    - 'mvn clean install'

test-account-query:
  stage: test
  tags:
    - shared-fi
  script:
    - 'cd account-query'
    - 'mvn clean install'

test-transaction-processor:
  stage: test
  tags:
    - shared-fi
  script:
    - 'cd transaction-processor'
    - 'mvn clean install'
