stages:
  - build
  - test

image: maven:latest

test-account-management:
  stage: test
  tags:
    - shared-fi
  script:
    - 'cd account-management'
    - 'mvn clean install'

test-account-query:
  stage: test
  image: docker
  tags:
    - shared-fi
  script:
    - 'docker-compose up -d'
    - 'cd account-query'
    - 'mvn clean install'
    - 'docker-compose down'

test-infrastructure:
  stage: test
  tags:
    - shared-fi
  script:
    - 'cd infrastructure'
    - 'mvn clean install'

test-transaction-processor:
  stage: test
  tags:
    - shared-fi
  script:
    - 'cd infrastructure'
    - 'mvn clean install'
    - 'cd ..'
    - 'cd transaction-processor'
    - 'mvn clean install'
