version: "3.9"
name: online-banking

services:

  banking-db:
    image: "postgres:16.2"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=banking
    volumes:
      - ./.docker/db/scripts:/docker-entrypoint-initdb.d
    
  account-management:
    image: account-management
    ports:
      - "8080:8080"
    
  account-query:
    image: account-query
    ports:
      - "8081:8081"

  transaction-processor:
    image: transaction-processor
    ports:
      - "8082:8082"

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9000:9090"
    volumes:
      - ./.docker/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./.docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./.docker/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./.docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./.docker/grafana/dashboards:/var/lib/grafana/dashboards

