CREATE SCHEMA IF NOT EXISTS bank_user;
CREATE USER "ACC_USER" WITH PASSWORD 'userAccPasswd';
ALTER ROLE "ACC_USER" SET SEARCH_PATH TO bank_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bank_user TO "ACC_USER";

CREATE SCHEMA IF NOT EXISTS bank_account;
CREATE USER "ACC_ACCOUNT" WITH PASSWORD 'accountAccPasswd';
ALTER ROLE "ACC_ACCOUNT" SET SEARCH_PATH TO bank_account;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bank_account TO "ACC_ACCOUNT";

CREATE SCHEMA IF NOT EXISTS bank_transaction;
CREATE USER "ACC_TRANSACTION" WITH PASSWORD 'transactionAccPasswd';
GRANT ALL PRIVILEGES ON SCHEMA bank_transaction TO "ACC_TRANSACTION";
ALTER ROLE "ACC_TRANSACTION" SET SEARCH_PATH TO bank_transaction;
