SET ROLE "ACC_ACCOUNT";
SET SEARCH_PATH TO bank_account;

-- CREATE TABLES

CREATE TABLE IF NOT EXISTS bal_transaction
(
    amount NUMERIC(38, 2),
    type SMALLINT,
    date TIMESTAMP(6) WITH TIME ZONE,
    id BIGINT PRIMARY KEY,
    process_id UUID,
    balance_id CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS balance
(
    amount NUMERIC(38, 2),
    balance_id CHARACTER VARYING(255) PRIMARY KEY
);

CREATE SEQUENCE bal_transaction_seq START WITH 1 INCREMENT BY 50;

ALTER TABLE bal_transaction ADD CONSTRAINT CONSTRAINT_FF CHECK(TYPE BETWEEN 0 AND 4);
ALTER TABLE bal_transaction ADD CONSTRAINT CONSTRAINT_F CHECK(TYPE BETWEEN 0 AND 4);
ALTER TABLE bal_transaction ADD CONSTRAINT FKICJDGHKQ3OQKDCDC6KKUJD6O3 FOREIGN KEY(BALANCE_ID) REFERENCES balance(BALANCE_ID);