server:
  port: 8081

db:
  hostname: localhost

spring:
  application:
    name: balance-query
  datasource:
    url: jdbc:postgresql://${db.hostname}:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_ACCOUNT
    password: accountAccPasswd

management:
  endpoints:
    web:
      exposure:
        include:
          health,metrics,prometheus