server:
  port: 8081

db:
  hostname: localhost

spring:
  application:
    name: balance-query
  datasource:
    url: jdbc:postgresql://${db.hostname}:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_ACCOUNT
    password: accountAccPasswd

management:
  info:
    env:
      enabled:
        true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          health,metrics,prometheus
  endpoint:
    health:
      enabled:
        true
    metrics:
      enabled:
        true
    prometheus:
      enabled:
        true
