db:
  hostname: localhost
spring:
  application:
    name: Transaction-Processor
  datasource:
    url: jdbc:postgresql://${db.hostname}:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_TRANSACTION
    password: transactionAccPasswd
  jpa:
    mapping-resources: hibernate/Transaction.hbm.xml