db:
  hostname: localhost
spring:
  application:
    name: Transaction-Processor
banking:
  apps:
    management:
      host: localhost
      port: 8080
      url: ${banking.apps.management.host}:${banking.apps.management.port}
    query:
      host: localhost
      port: 8081
      url: ${banking.apps.query.host}:${banking.apps.query.port}
    
  datasource:
    url: jdbc:postgresql://${db.hostname}:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_TRANSACTION
    password: transactionAccPasswd
  jpa:
    mapping-resources: hibernate/Transaction.hbm.xml
