spring:
  application:
    name: Transaction-Processor
  datasource:
    url: jdbc:postgresql://banking-db:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_TRANSACTION
    password: transactionAccPasswd
  jpa:
    mapping-resources: hibernate/Transaction.hbm.xml