openapi: 3.0.1
info:
  title: Transaction Processor API
  description: Public API of Online Banking System - Transaction Processor
  version: 1.0.0
servers:
  - url: "localhost:8081"
tags:
  - name: Transaction
    description: API for transaction requests
  - name: ProcessorApi
    description: API for administration of transaction processes

paths:
  /transaction/v1/process:
    put:
      tags:
        - Transaction
      operationId: create-transaction-process
      summary: Create a new request for a transaction to be processed
      description: |
        Method starts a new process for processing a transaction request defined by the input.
        After a process is created successfully, it is being handled asynchronous. Method replies with a JSON object
        containing a unique identifier of the created process, status and a message explaining the status.
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/TransactionDto'
      responses: 
        '201':
          description: Process created, sent unique identifier assigned to new process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessDto'

  /transaction/v1/status:
    get:
      tags:
        - Transaction
      operationId: status
      summary: Get information about a existing transaction process
      description: |
        Method finds an existing process for a transaction request, returning all information about it's state
        and further information regarding errors.
      parameters:
        - in: header
          name: x-process-uuid
          schema:
            type: string
            format: uuid
          required: true
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessDetailDto'
        '404':
          description: Resource or process by UUID not found

  /transaction/v1/revert:
    post:
      tags:
        - Transaction
      operationId: revert-transaction-process
      summary: Revert a transaction
      description: |
        Method finds an existing process for a transaction request, which has been executed successfully, and reverts
        the changes done
      parameters:
        - in: header
          name: x-process-uuid
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Process found and created new process reverting changes in accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessDto'
        '400':
          description: Process found by UUID but not in expected state (PROCESSED)
        '404':
          description: Resource or process by UUID not found

components: 
  schemas: 
    TransactionTypeDto:
      type: string
      enum:
        - WITHDRAWAL
        - DEPOSIT
        - TRANSFER
        - SCHEDULED
      description: Enumaration defining a type for a transaction. Each type may have different certain implementations and validations.
      
    AccountDto:
      type: object
      properties:
        accountNumber:
          type: string
          description: Account number
    
    MoneyDto:
      type: object
      properties: 
        amount: 
          type: number
        currency:
          type: string
          description: Currency code, short abbreviation of 3 characters such as 'EUR' or 'CZK'.
    
    TransactionDto:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/AccountDto'
        target:
          $ref: '#/components/schemas/AccountDto'
        type:
          $ref: '#/components/schemas/TransactionTypeDto'
        amount:
          $ref: '#/components/schemas/MoneyDto'
        detail:
          type: string
          description: Message or detail for transaction, holding user specified information
    
    StatusDto:
      type: string
      enum:
        - CREATED
        - PENDING
        - PROCESSED
        - FAILED
          
    ProcessDto:
      type: object
      properties:
        identifier:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/StatusDto'
        info:
          type: string
          description: Message detail regarding process status, e.g. reason of failure or result of process.
    
    ProcessDetailDto:
      allOf:
        - $ref: '#/components/schemas/ProcessDto'
        - $ref: '#/components/schemas/TransactionDto'
        