package cz.muni.pa165.banking.application.repository;

import cz.muni.pa165.banking.domain.account.Account;
import cz.muni.pa165.banking.domain.account.repository.AccountRepository;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.Map;

@Repository
public class AccountRepositoryImpl implements AccountRepository {

    private Long sequencer = 1L;
    private Map<Long, Account> accounts = new HashMap<>();

    @Override
    public Account addAccount(Account account) {
        account.setId(sequencer);
        account.setAccountNumber("CZ00000000000000000000000" + sequencer); // TODO Milestone2 -> generated by DB on create?
        accounts.put(sequencer++, account);
        return account;
    }

    @Override
    public Account getById(Long id) {
        return accounts.get(id);
    }

    @Override
    public Account getByAccountNumber(String accountNumber) {
        return accounts.values().stream()
                .filter(account -> account.getAccountNumber().equals(accountNumber))
                .findFirst()
                .orElse(null);
    }

}
