server:
  port: 8080

db:
  hostname: localhost

scheduled:
  cron:
    expression: "0 0 0 * * MON" # Execute every Monday at midnight
    
spring:
  application:
    name: account-management
  datasource:
    url: jdbc:postgresql://${db.hostname}:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_USER
    password: userAccPasswd
    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG
  jpa:
    show-sql: true
              