server:
  port: 8080

db:
  hostname: localhost

banking:
  apps:
    query:
      host: localhost
      port: 8081
      url: ${banking.apps.query.host}:${banking.apps.query.port}

spring:
  application:
    name: account-management
  datasource:
    url: jdbc:postgresql://${db.hostname}:5432/banking
    driver-class-name: org.postgresql.Driver
    username: ACC_USER
    password: userAccPasswd
  jpa:
    show-sql: true

management:
  info:
    env:
      enabled:
        true
  endpoints:
    web:
      exposure:
        include:
          health,metrics,prometheus
  endpoint:
    health:
      enabled:
        true
    metrics:
      enabled:
        true
